Django/lab1/bookstore/book/urls.py
from django.urls import path
from .views import index , get_all_books, book_detail, book_delete, book_update, book_create, add_book

app_name = 'book'

# http://localhost:8000/post/2/comment/1
urlpatterns = [
    path('index', index, name='book-index'),
    path('book_list/', get_all_books, name="book-list"),
    path('book_create',book_create,name="book-create"),
    path('add_new_book',add_book,name="book-add"),
    path('book_detail/<int:book_id>', book_detail, name="book-detail"),
    path('book_delete/<int:book_id>', book_delete, name="book-delete"),
    path('book_update/<int:book_id>', book_update, name="book-update"),
]

Django/lab1/bookstore/book/models.py
from django.db import models

# Create your models here.

Django/lab1/bookstore/book/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect

# Create your views here.

def index(request):
    print(request.body)
    print("hello")
    return render(request, 'main/base_layout.html')

books_list = [
    {
        'title':'Book1',
        'id':1,
        'description':'book one description',
        'quantity':3
    },
    {
       'title':'Book2',
        'id':2,
        'description':'book two description',
        'quantity':5 
    },
    {
       'title':'Book3',
        'id':3,
        'description':'book three description',
        'quantity':1
    },
]

def get_all_books(request):
    my_context = {'books_list': books_list}
    return render(request, 'book/book_list.html', context=my_context)

def _get_book(book_id):
    for book in books_list:
        if 'id' in book and book['id'] == book_id:
            return book
    return None

def book_detail(request, **kwrgs):
    book_id = kwrgs.get('book_id')
    book_object = _get_book(book_id)
    if book_object:
        my_context = {
            'book_id': book_object.get('id'),
            'book_title': book_object.get('title'),
            'book_quantity': book_object.get('quantity'),
            'book_description': book_object.get('description')
        }
    else:
        my_context = {
            'book_id': "unavailable",
            'book_title': "unavailable",
            'book_quantity': "unavailable",
            'book_description': "unavailable" 
        }

    return render(request, 'book/book_details.html', context=my_context)

def book_delete(request, **kwargs):
    book_id = kwargs.get('book_id')
    book_object = _get_book(book_id)
    if book_object:
        books_list.remove(book_object)
    return redirect('book:book-list') 

def book_update(request, **kwargs):
    book_id = kwargs.get('book_id')
    book_object = _get_book(book_id)
    for book in books_list:
        if book == book_object:
            book['title'] = f"{book_object['title']} is updated"       
    return redirect('book:book-list') 

def book_create(request):
    return render(request, 'book/book_create.html')

def add_book(request):
    if request.method == 'POST':
        my_context = {
            'id': request.POST['id'],
            'title': request.POST['title'],
            'quantity': request.POST['quantity'],
            'description': request.POST['description']
        }
        books_list.append(my_context)
    all_books = {'books_list': books_list}
    return render(request, 'book/book_list.html', context=all_books)
    



Django/lab1/bookstore/book/templates/book/book_create.html
{% extends 'main/base_layout.html' %}

{# override block title #}

{% block title %}
    NEW BOOK
{% endblock %}

{# override body #}
{% block main-content %}
<h1> New Book </h1>
 
<form method="post" class="container" action="{% url 'book:book-add'%}">
{% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputID1" class="form-label">ID</label>
      <input type="text" class="form-control" id="exampleInputID1" name="id" >
    </div>
    <div class="mb-3">
        <label for="exampleInputTitle" class="form-label">Title</label>
        <input type="text" class="form-control" id="exampleInputTitle" name="title" >
    </div>
    <div class="mb-3">
        <label for="exampleInputDesc" class="form-label">Description</label>
        <input type="text" class="form-control" id="exampleInputDesc" name="description" >
    </div>
    <div class="mb-3">
        <label for="exampleInputQuantity" class="form-label">Quantity</label>
        <input type="number" class="form-control" id="exampleInputQuantity" name="quantity" >
    </div>
    <button type="submit" class="btn btn-primary" >Submit</button>
  </form>

{% endblock %}

Django/lab1/bookstore/book/templates/book/book_details.html
{% extends 'main/base_layout.html' %}


{% block main-content %}
 <h1> Book Details </h1>
 <table class="table">
    <thead>
        <tr>
            <td> ID </td>
            <td> Title </td>
            <td> Quantity </td>
            <td> Description </td>
        </tr>
    </thead>
    <tbody>

        <tr>
            <td>{{ book_id }} </td>
            <td>{{ book_title }} </td>
            <td> {{ book_quantity }}</td>
            <td> {{ book_description }} </td>
        </tr>
    </tbody>

 </table>


{% endblock %}

Django/lab1/bookstore/book/templates/book/book_list.html
{% extends 'main/base_layout.html' %}

{# override block title #}

{% block title %}
    TODO task list
{% endblock %}

{# override body #}
{% block main-content %}
<table class="table table-condensed">
    <thead>
       <tr>
           <td> ID </td>
           <td> Title </td>
           <td> Description </td>
           <td> Quantity </td>
       </tr>
    </thead>
    
    <tbody>
       {% for book in books_list%}
      <tr>
       <td> {{book.id}} </td>
       <td> {{book.title}} </td>
       <td> {{book.description}} </td>
       <td>  {{book.quantity}} </td>
       <td> 
           <a class="btn btn-primary" href="{% url 'book:book-detail' book.id %}"> View</a>
           <a class="btn btn-info" href="{% url 'book:book-update' book.id %}"> Update</a>
           <a class="btn btn-danger" href="{% url 'book:book-delete' book.id %}"> Delete</a> 
       </td>
      </tr>
      {% empty %}
      <tr>
       <td colspan="3" class="text-center">There are no books</td>
      </tr>
   {% endfor %}
    </tbody>
   </table>
   <a class="btn btn-success" href="{% url 'book:book-create'%}">Add book</a>
   {% endblock %}